ansible_connection: ENC[AES256_GCM,data:bWW+q88=,iv:/1pX7VVLgWHkHtYm4cxarVPNvcyhZWKkJaoBvf73E3E=,tag:ryHQjf9OA0GbEAKRqJQZmw==,type:str]
ansible_become_password: ENC[AES256_GCM,data:WOYpgTbuHEY0,iv:qHzMei4IxmKorUhQGlrogpuV5pBAY4X68v6Z/zn9XpA=,tag:xS7ghlaS2rA0143HpDCYmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-22T03:51:03Z"
    mac: ENC[AES256_GCM,data:vE3j39vyuRtNjzfAXuln0RL91mnX24r7OaaPGd0A9MZSBPBae/CuqzX2MNOC2RLmbX1gDfGsAp23Uz+kCJ/hA2RIqLUQvYMYLjpMZUH7c3OKBQ5pLqKRcjk6nb30VpOePLQTuydiwcW34mBLpJsprcEE/7FjYrmw5UYYYcOk2YU=,iv:Be8afUL69DAZ5x2yizAmqI0ubhMHZuhaLgHqZFe74FM=,tag:JEdGb0gY3QjFaaK8UpY89Q==,type:str]
    pgp:
        - created_at: "2022-08-22T03:44:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA7LF3mkfbQTxARAAoFtPDlKuODG26Hb0D4nlCXEPcgDptHQXDeMppxLXGz8m
            e6iXB+TdhzrCnENUk0FwRTirzxLWfp0PoqPmSvaf8CdQihXXEEg0GGgucyk07pjU
            qeG1HvObvIRcaCEQHeWpfJ9U4+JhiNOw2MuSBhlKjLIuXnxTz407jygQppU/BmpT
            QVt4vhGSYLjUD4Waqa1My+iWlPlVd2cFvmvHgvBgpCwkwoIpsBo74Dlw8YZ6UfOV
            YEAyeVZlpK/jyiqUlkT2KwGANC7czDA4ft2FUjXDnaU3/Y3PDtvsIArKMTioBoKy
            KUtuKIuNFV3I/WiTu02gLznQgFsj2MpHU9aC35R9dtn67Yu4RCRgdDuurFyJSit3
            jfjNqhqVU1P0NPyD7FAK69885PgBzUyA5lCDjImvhhlnTiu07D+/x1nntqM8dJfx
            XefCgzjwHFAFrOzwXjMavNiDOK1vXsgKLiM2xHF1p20D+nJ+M6/ujKWephYM7Fll
            9m7DfDemvBcroA6CLySLWYRWunyY8PWwe2j8oFZjfWj2wuTBpIqhntIz4bfi/J6f
            LPyqcKh9gBJppPlP1s/qw4fU8hISDOPjCRbhBgNhtbjpmt8zND2qlpD7Y+KIGos2
            acLy1jMSbFiVLRmylKon1RGoIpX/QJwBNNk5ZelU+4+28knm9TSFH1i7kHj8GpHS
            UQGAxzK8ZAmXKPG/OqxeMsL7/rwgmC7pNED6bf+maMO8ioKTMvWTiMnmrrQ4sNN2
            fP1OvUHDYeIBihx0acsQlVWxgADyT0UdOkZpIAZV6KKvyQ==
            =0jQo
            -----END PGP MESSAGE-----
          fp: FFF6DDE2181C1F55E8885470C02D23F17563AA95
    unencrypted_suffix: _unencrypted
    version: 3.7.3
